export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const UPDATE_COLUMN_ORDER = "UPDATE_COLUMN_ORDER";
export const NO_CHANGE = "NO_CHANGE";
export const INITAL_DATA = "INITAL_DATA";

export const ADD_COLUMN = "ADD_COLUMN";
export const DELETE_COLUMN = "DELETE_COLUMN";

export const RAISE_MESSAGE = "RAISE_MESSAGE";
